#!/bin/bash

# Production Deployment to Render
# This script automates deployment to Render platform

set -e

echo "🚀 Deploying to Render"
echo "===================="
echo ""
echo "Render Deployment Instructions:"
echo "================================"
echo ""
echo "1. Backend Deployment"
echo "   - Go to: https://dashboard.render.com"
echo "   - Click 'New +'  → 'Web Service'"
echo "   - Connect your GitHub repository"
echo "   - Configuration:"
echo "     Build Command: cd backend && npm install && npm run build"
echo "     Start Command: cd backend && npm start"
echo "   - Environment Variables:"
echo "     JWT_SECRET: (generate with: openssl rand -base64 32)"
echo "     NODE_ENV: production"
echo "     PORT: 5000"
echo "     DATABASE_PATH: /var/lib/spendsmart/app.db"
echo "   - Deploy!"
echo ""
echo "2. Frontend Deployment"
echo "   - Option A: Deploy on Render"
echo "     - Click 'New +' → 'Static Site'"
echo "     - Connect your GitHub repository"
echo "     - Build Command: npm run build"
echo "     - Publish Directory: dist"
echo ""
echo "   - Option B: Deploy on Vercel (Recommended)"
echo "     - Go to: https://vercel.com/new"
echo "     - Import GitHub repository"
echo "     - Build Command: npm run build"
echo "     - Output Directory: dist"
echo "     - Environment Variable:"
echo "       VITE_API_BASE: https://your-backend-render-url/api"
echo ""
echo "3. After Deployment"
echo "   - Get your backend URL from Render dashboard"
echo "   - Update VITE_API_BASE in .env.production"
echo "   - Redeploy frontend with updated API base"
echo "   - Test: curl https://your-backend-url/api/health"
echo ""
echo "📖 For detailed instructions, see: PRODUCTION_SETUP.md"
